# Generated by Django 5.1.5 on 2025-02-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
        ('app', '0005_post_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.DeleteModel(
            name='CountLink',
        ),
    ]
