# Generated by Django 5.1.5 on 2025-02-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
