# Generated by Django 5.1.5 on 2025-02-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='view_count',
            new_name='views',
        ),
    ]
